import { describe, expect, it } from 'vitest'
import { readFileSync } from 'node:fs'
import {
  AGENT_SKILL_PATH,
  SKILL_SOURCE_PATH,
  normalizeGeneratedText,
  renderAgentSkill,
} from './skill.js'
import { contextDigest } from './sync.js'

const BODY = [
  '# DSH Plugin Development',
  '',
  'Use the forge as the agent-owned environment.',
  '',
  '## Contract library',
  '',
  '- [Harness contracts](../../../context/harness-contracts.md)',
].join('\n')

describe('portable agent skill renderer', () => {
  it('renders stable Agent Skills frontmatter and one canonical heading', () => {
    const rendered = renderAgentSkill({
      body: BODY,
      documents: ['alpha\n', 'beta\n'],
    })

    expect(rendered).toMatch(
      /^---\nname: dsh-plugin-development\ndescription: Use when creating, studying, debugging, or verifying a DeepSeek Harness plugin in dsh-lab\.\n---\n/,
    )
    expect(rendered.match(/^# /gm)).toHaveLength(1)
    expect(rendered).toContain(
      '# DSH Plugin Development\n\n> Generated from `context/*`; do not edit this file directly.\n',
    )
    expect(rendered).toMatch(/^> context version: [0-9a-f]{12}$/m)
    expect(rendered).toContain('## Contract library')
    expect(rendered.endsWith('\n')).toBe(true)
    expect(rendered.endsWith('\n\n')).toBe(false)
    expect(rendered).not.toContain('\r')
  })

  it('is deterministic and changes when canonical context changes', () => {
    const first = renderAgentSkill({ body: BODY, documents: ['alpha', 'beta'] })
    const second = renderAgentSkill({ body: BODY, documents: ['alpha', 'beta'] })
    const changed = renderAgentSkill({ body: BODY, documents: ['alpha', 'beta changed'] })

    expect(second).toBe(first)
    expect(changed).not.toBe(first)
  })

  it('normalizes platform line endings before rendering and comparison', () => {
    expect(normalizeGeneratedText('a\r\nb\rc\n')).toBe('a\nb\nc\n')
    expect(
      renderAgentSkill({ body: BODY.replaceAll('\n', '\r\n'), documents: ['a\r\n'] }),
    ).toBe(renderAgentSkill({ body: BODY, documents: ['a\n'] }))
    expect(contextDigest(['a\r\n'])).toBe(contextDigest(['a\n']))
  })

  it('uses unambiguous document boundaries in the shared digest', () => {
    expect(contextDigest(['ab', 'c'])).not.toBe(contextDigest(['a', 'bc']))
    expect(contextDigest([''])).not.toBe(contextDigest(['', '']))
  })

  it('rejects a canonical body with the wrong or duplicate top-level heading', () => {
    expect(() => renderAgentSkill({ body: '# Wrong', documents: [] })).toThrow(
      /# DSH Plugin Development/,
    )
    expect(() =>
      renderAgentSkill({
        body: `${BODY}\n\n# Second heading`,
        documents: [],
      }),
    ).toThrow(/top-level heading/i)
  })

  it('rejects alternate CommonMark top-level headings after the canonical H1', () => {
    expect(() =>
      renderAgentSkill({
        body: `${BODY}\n\nSecond heading\n===`,
        documents: [],
      }),
    ).toThrow(/top-level heading/i)
    expect(() =>
      renderAgentSkill({
        body: `${BODY}\n\n#\tSecond heading`,
        documents: [],
      }),
    ).toThrow(/top-level heading/i)
  })

  it('does not parse heading-like lines inside a longer fenced code block', () => {
    const body = [
      BODY,
      '',
      '````markdown',
      '~~~',
      '#\tThis is code, not a heading',
      '```',
      '````',
    ].join('\n')

    expect(() => renderAgentSkill({ body, documents: [] })).not.toThrow()
  })

  it('fixes the only portable projection and canonical source paths', () => {
    expect(AGENT_SKILL_PATH).toBe('.agents/skills/dsh-plugin-development/SKILL.md')
    expect(SKILL_SOURCE_PATH).toBe('context/dsh-plugin-development-skill.md')
  })

  it('routes agents through the separate minimal UI verification protocol without owning their browser workflow', () => {
    const source = readFileSync(new URL('../../context/dsh-plugin-development-skill.md', import.meta.url), 'utf8')
    const generated = readFileSync(new URL('../../.agents/skills/dsh-plugin-development/SKILL.md', import.meta.url), 'utf8')

    for (const guidance of [source, generated]) {
      expect(guidance).toMatch(/lab ui start[\s\S]*lab ui status[\s\S]*lab ui finish[\s\S]*lab ui abort/i)
      expect(guidance).toMatch(/external[\s\S]{0,120}(?:browser|vision)[\s\S]{0,200}(?:agent|harness)/i)
      expect(guidance).toMatch(/temporary[\s\S]{0,160}(?:isolated|session)[\s\S]{0,160}runtime/i)
      expect(guidance).toMatch(/minimal[\s\S]{0,120}(?:verdict|evidence|result)/i)
      expect(guidance).toMatch(/screenshots?[\s\S]{0,120}(?:transient|not retained|not stored)/i)
      expect(guidance).toMatch(/SDD[\s\S]{0,80}(?:advisory|recommend|chosen)/i)
      expect(guidance).not.toMatch(/(?:must|required to)\s+(?:use|run)\s+(?:SDD|agent-browser|Codex|Pi|DSH)/i)
    }
  })
})
