import { createHash } from 'node:crypto'

export const AGENT_SKILL_PATH = '.agents/skills/dsh-plugin-development/SKILL.md'
export const SKILL_SOURCE_PATH = 'context/dsh-plugin-development-skill.md'

export function normalizeGeneratedText(text: string): string {
  return text.replaceAll('\r\n', '\n').replaceAll('\r', '\n')
}

export function contextDigest(reads: readonly string[]): string {
  const hash = createHash('sha256')
  for (const read of reads) {
    const bytes = Buffer.from(normalizeGeneratedText(read), 'utf8')
    hash.update(String(bytes.byteLength))
    hash.update('\0')
    hash.update(bytes)
  }
  return hash.digest('hex').slice(0, 12)
}

export function renderAgentSkill(input: {
  body: string
  documents: readonly string[]
}): string {
  const body = normalizeGeneratedText(input.body).trimEnd()
  const lines = body.split('\n')
  if (lines[0] !== '# DSH Plugin Development') {
    throw new Error('canonical body must start with # DSH Plugin Development')
  }
  if (hasAlternateTopLevelHeading(lines.slice(1))) {
    throw new Error('canonical body must contain only one top-level heading')
  }

  const remainder = lines.slice(1).join('\n').replace(/^\n*/, '')
  const note = '> Generated from `context/*`; do not edit this file directly.'
  const version = `> context version: ${contextDigest(input.documents)}`
  return normalizeGeneratedText([
    '---',
    'name: dsh-plugin-development',
    'description: Use when creating, studying, debugging, or verifying a DeepSeek Harness plugin in dsh-lab.',
    '---',
    '',
    '# DSH Plugin Development',
    '',
    note,
    version,
    '> regenerate with `pnpm lab sync-context`',
    '',
    remainder,
  ].join('\n')).replace(/\n*$/, '\n')
}

function hasAlternateTopLevelHeading(lines: readonly string[]): boolean {
  let fence: { marker: '`' | '~'; length: number } | undefined
  let previous: string | undefined

  for (const line of lines) {
    const run = /^ {0,3}(`+|~+)(.*)$/.exec(line)
    const marker = run?.[1]
    if (fence) {
      const closing = marker
      if (
        closing &&
        closing[0] === fence.marker &&
        closing.length >= fence.length &&
        /^[ \t]*$/.test(run?.[2] ?? '')
      ) {
        fence = undefined
      }
      previous = undefined
      continue
    }
    if (marker && marker.length >= 3) {
      fence = { marker: marker[0] as '`' | '~', length: marker.length }
      previous = undefined
      continue
    }

    // A single-hash ATX heading may use spaces, a tab, or no heading text.
    // `##` and deeper headings are valid body content and are intentionally
    // left alone.
    if (/^ {0,3}#[ \t]+/.test(line) || /^ {0,3}#$/.test(line)) return true

    // A Setext underline makes the preceding paragraph a top-level H1. Skip
    // indented code, whose equals signs are ordinary body content.
    if (!/^(?: {4}|\t)/.test(line) && /^ {0,3}=+\s*$/.test(line)) {
      if (previous !== undefined && previous.trim() !== '') return true
    }

    previous = line
  }
  return false
}
