import { contextDigest } from './sync.js'

export const AGENT_SKILL_PATH = '.agents/skills/dsh-plugin-development/SKILL.md'
export const SKILL_SOURCE_PATH = 'context/dsh-plugin-development-skill.md'

export function normalizeGeneratedText(text: string): string {
  return text.replaceAll('\r\n', '\n').replaceAll('\r', '\n')
}

export function renderAgentSkill(input: {
  body: string
  documents: readonly string[]
}): string {
  const body = normalizeGeneratedText(input.body).trimEnd()
  const lines = body.split('\n')
  if (lines[0] !== '# DSH Plugin Development') {
    throw new Error('canonical body must start with # DSH Plugin Development')
  }
  if (lines.slice(1).some(line => line.startsWith('# '))) {
    throw new Error('canonical body must contain only one top-level heading')
  }

  const remainder = lines.slice(1).join('\n').replace(/^\n*/, '')
  const note = '> Generated from `context/*`; do not edit this file directly.'
  const version = `> context version: ${contextDigest(input.documents)}`
  return normalizeGeneratedText([
    '---',
    'name: dsh-plugin-development',
    'description: Use when creating, studying, debugging, or verifying a DeepSeek Harness plugin in dsh-lab.',
    '---',
    '',
    '# DSH Plugin Development',
    '',
    note,
    version,
    '',
    remainder,
  ].join('\n')).replace(/\n*$/, '\n')
}
