import { describe, expect, it } from 'vitest'
import {
  AGENT_SKILL_PATH,
  SKILL_SOURCE_PATH,
  normalizeGeneratedText,
  renderAgentSkill,
} from './skill.js'
import { contextDigest } from './sync.js'

const BODY = [
  '# DSH Plugin Development',
  '',
  'Use the forge as the agent-owned environment.',
  '',
  '## Contract library',
  '',
  '- [Harness contracts](../../../context/harness-contracts.md)',
].join('\n')

describe('portable agent skill renderer', () => {
  it('renders stable Agent Skills frontmatter and one canonical heading', () => {
    const rendered = renderAgentSkill({
      body: BODY,
      documents: ['alpha\n', 'beta\n'],
    })

    expect(rendered).toMatch(
      /^---\nname: dsh-plugin-development\ndescription: Use when creating, studying, debugging, or verifying a DeepSeek Harness plugin in dsh-lab\.\n---\n/,
    )
    expect(rendered.match(/^# /gm)).toHaveLength(1)
    expect(rendered).toContain(
      '# DSH Plugin Development\n\n> Generated from `context/*`; do not edit this file directly.\n',
    )
    expect(rendered).toMatch(/^> context version: [0-9a-f]{12}$/m)
    expect(rendered).toContain('## Contract library')
    expect(rendered.endsWith('\n')).toBe(true)
    expect(rendered.endsWith('\n\n')).toBe(false)
    expect(rendered).not.toContain('\r')
  })

  it('is deterministic and changes when canonical context changes', () => {
    const first = renderAgentSkill({ body: BODY, documents: ['alpha', 'beta'] })
    const second = renderAgentSkill({ body: BODY, documents: ['alpha', 'beta'] })
    const changed = renderAgentSkill({ body: BODY, documents: ['alpha', 'beta changed'] })

    expect(second).toBe(first)
    expect(changed).not.toBe(first)
  })

  it('normalizes platform line endings before rendering and comparison', () => {
    expect(normalizeGeneratedText('a\r\nb\rc\n')).toBe('a\nb\nc\n')
    expect(
      renderAgentSkill({ body: BODY.replaceAll('\n', '\r\n'), documents: ['a\r\n'] }),
    ).toBe(renderAgentSkill({ body: BODY, documents: ['a\n'] }))
    expect(contextDigest(['a\r\n'])).toBe(contextDigest(['a\n']))
  })

  it('uses unambiguous document boundaries in the shared digest', () => {
    expect(contextDigest(['ab', 'c'])).not.toBe(contextDigest(['a', 'bc']))
    expect(contextDigest([''])).not.toBe(contextDigest(['', '']))
  })

  it('rejects a canonical body with the wrong or duplicate top-level heading', () => {
    expect(() => renderAgentSkill({ body: '# Wrong', documents: [] })).toThrow(
      /# DSH Plugin Development/,
    )
    expect(() =>
      renderAgentSkill({
        body: `${BODY}\n\n# Second heading`,
        documents: [],
      }),
    ).toThrow(/top-level heading/i)
  })

  it('rejects alternate CommonMark top-level headings after the canonical H1', () => {
    expect(() =>
      renderAgentSkill({
        body: `${BODY}\n\nSecond heading\n===`,
        documents: [],
      }),
    ).toThrow(/top-level heading/i)
    expect(() =>
      renderAgentSkill({
        body: `${BODY}\n\n#\tSecond heading`,
        documents: [],
      }),
    ).toThrow(/top-level heading/i)
  })

  it('fixes the only portable projection and canonical source paths', () => {
    expect(AGENT_SKILL_PATH).toBe('.agents/skills/dsh-plugin-development/SKILL.md')
    expect(SKILL_SOURCE_PATH).toBe('context/dsh-plugin-development-skill.md')
  })
})
