import { createHash } from 'node:crypto'

export const AGENT_SKILL_PATH = '.agents/skills/dsh-plugin-development/SKILL.md'
export const SKILL_SOURCE_PATH = 'context/dsh-plugin-development-skill.md'

export function normalizeGeneratedText(text: string): string {
  return text.replaceAll('\r\n', '\n').replaceAll('\r', '\n')
}

export function contextDigest(reads: readonly string[]): string {
  const hash = createHash('sha256')
  for (const read of reads) {
    const bytes = Buffer.from(normalizeGeneratedText(read), 'utf8')
    hash.update(String(bytes.byteLength))
    hash.update('\0')
    hash.update(bytes)
  }
  return hash.digest('hex').slice(0, 12)
}

export function renderAgentSkill(input: {
  body: string
  documents: readonly string[]
}): string {
  const body = normalizeGeneratedText(input.body).trimEnd()
  const lines = body.split('\n')
  if (lines[0] !== '# DSH Plugin Development') {
    throw new Error('canonical body must start with # DSH Plugin Development')
  }
  if (lines.slice(1).some(line => line.startsWith('# '))) {
    throw new Error('canonical body must contain only one top-level heading')
  }

  const remainder = lines.slice(1).join('\n').replace(/^\n*/, '')
  const note = '> Generated from `context/*`; do not edit this file directly.'
  const version = `> context version: ${contextDigest(input.documents)}`
  return normalizeGeneratedText([
    '---',
    'name: dsh-plugin-development',
    'description: Use when creating, studying, debugging, or verifying a DeepSeek Harness plugin in dsh-lab.',
    '---',
    '',
    '# DSH Plugin Development',
    '',
    note,
    version,
    '> regenerate with `pnpm lab sync-context`',
    '',
    remainder,
  ].join('\n')).replace(/\n*$/, '\n')
}
